project:
  type: website


website:
  title: "Phillip P. Schmutz"
  site-url: https://phillipschmutz.github.io
  favicon: files/favicon.png

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: courses.qmd
        text: Teaching
      - href: cv.qmd
        text: CV
      - href: cgmlab.qmd
        text: Research

    right:
      - icon: github
        href: https://github.com/phillipschmutz
      - icon: journal
        href: https://scholar.google.com/citations?user=6eBNIrgAAAAJ&hl=en
      - icon: envelope
        href: mailto:pschmutz@uwf.edu


  page-footer:
    right: "© 2026 pschmutz, University of West Florida"

format:
  html:
    theme: flatly
    toc: false
    page-layout: full

    css:
      - styles.css
      - homepage.css
      - publications.css

    include-in-header:
      text: |
        <!-- Font Awesome -->
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css">

execute:
  freeze: auto


