project:
  type: website
  
  
website:
  title: "Phillip Schmutz, Ph.D."
  site-url: "https://phillipschmutz.github.io"
  
  navbar:
    collapse-below: sm 
    left:
      - text: "Home"
        href: index2.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Courses"
        href: courses.qmd
      - text: "Research Lab"
        menu:
          - text: "Computational Geomorphology and Modeling (CGM) Lab"
            href: cgmlab.qmd

  page-footer:
    right: "© 2026 Phillip P. Schmutz, University of West Florida"
    
    
format:
  html:
    theme: flatly
    css: styles.css
    toc: false
    mainfont: Arial
    page-layout: full
