---
title: "CV"
---
### Dr. Phillip P. Schmutz
Associate Professor and Department Chair <br>
Department of Earth & Env. Sciences

### Education:
- *Ph.D.*: Louisiana State University, 2014
- *M.S.*: Louisiana State University, 2007
- *B.S.*: Baylor University, 2004

### Research Interests: 
- Topical: Coastal & Aeolian Geomorphology, 
- Systematic: Dune Restoration, Sea Turtle Nesting Habitat, Ecogeomorphic Modeling, Unoccupied Aerial Vehicles (UAV’s), Instrumentation Development & Design, Statistical Modeling

### Work Experience:
- Fall 2022 - present
  - Department Chair
  - Department of Earth and Environmental Sciences
  - University of West Florida

- Fall 2021 - present
  - Associate Professor
  - Department of Earth and Environmental Sciences
  - University of West Florida

- Fall 2015 - Fall 2021
  - Assistant Professor
  - Department of Earth and Environmental Sciences
  - University of West Florida

- Spring 2015 - Fall 2015
  - Postdoctoral Research Associate
  - Department of Geology and Geophysics
  - Texas A&M University
  
### Technical Skills:
- Programming Languages:
  - R (intermediate)
  - Python (elementary)
- GIS - Geographic Information Systems
  - ArcGIS Pro
- UAV Structure from Motion (SfM)
  - Agisoft Metashape
  - Pix4D Mapper