---
title: "GEO 4221 - Coastal Morphology"
---

## Course Overview

This course is an introduction to the world's coastal landforms, with emphasis upon dominant processes (especially waves, tides, and currents), geographical variations, human impacts and policies, and environmental concerns. 


## Student Learning Objectives (SLOs)
- Define coastal processes (i.e., wave, wind, tides, etc.)
- Describe the relationship between coastal landforms and key processes
- Illustrate how humans are adapting to current coastal management challenges
- Synthesize scholarship/research articles in the field of coastal geomorphology
- Evaluate the relevance of scholarship/research articles through the examination of current events


## Topics
- History of Coastal Science
- Waves
- Sea-Level Variations
- Tides & Tidal Currents
- Rocky Coasts
- Barrier Islands
- Beach and Dune Environments
- Wetlands and Estuaries
- Coastal Management

## Course Materials
- [Syllabus]()
- [Calendar]()

- Textbook: [Introduction to Coastal Processes and Geomorphology, 2nd Edition, Masselink, Hughes, and Knight](https://doi.org/10.4324/9780203785461)

## Assignments
- Two Examinations [25% eac -- 50% total]
- Seminar Days: Article Synopsis & Discussion [20%]
- History of Coastal Geomorphology Project & Presentation [30%]


